export enum CategoryType {
  ADMINISTRATIVE_BLOCK = 'administrative-block',
  AMPHI = 'amphi',
  CANTEEN = 'canteen',
  CLASSROOM = 'classroom',
  CLASSROOM_BLOCK = 'classroom-block',
  FACULTY = 'faculty',
  HEALTH_CENTER = 'health-center',
  LAB = 'lab',
  LIBRARY = 'library',
  MARKET_CENTER = 'market-center',
  OFFICE = 'office',
  PRINTING_SPOT = 'printing-spot',
  SPORT_PITCH = 'sport-pitch',
  TOILET = 'toilet',
  UB_HOSTEL = 'ub-hostel',
}
